### ISSUE TITLE
Essa atribuição tem que estar fora da exibição do mapa

### ISSUE THREAD

**Issue by fsantanna** [DanielLessa96/LP1#9]
https://github.com/DanielLessa96/LP1/blob/78fe4967c0ca82ec1569c12996ab8451f0b5931a/Personagem/personagem.c#L54

Você precisa colocar os personagens no mapa em um outro `for` antes desse.

**Comment by DanielLessa96** [comment]
Já mudei.

**Comment by fsantanna** [comment]
Ainda não está bom.
Precisa de um `for` antes de gerar os personagens para "zerar" o mapa.
Ao ler os personagens, você pode acessar o mapa diretamente através da posição, sem a necessidade de um outro `for` dentro.

**Comment by DanielLessa96** [comment]
Zerei o mapa antes de gerar os personagens. Mas não usei um for.
